schema:
  version: 1

event:
  name: event_test
  version: 1

types:
  $File:
    owner:
      of: array($User)
    name:
      of: string
    size:
      of: double
    quantity:
      of: long

  $User:
    name:
      of: string
      is:
        - required
        - encrypted
    friend:
      of: $User
    birthdate:
      of: date(yyyy/mm/dd)
      is:
        - required
        - encrypted
    gender:
      of: string
    height:
      of: float
    age:
      of: int

validation:
  payload:
    users:
      of: array($User)
      is:
        - required
    file:
      of: $File
    name:
      of: string
      is:
        - required
  identity:
    userId:
      of: long
      is:
        - required
  metadata:
    origin:
        of: string
        is:
          - required