schema:
  version: 1

event_name: event_test
event_version: 1

validation:
  payload:
    key1:
      type: string
      required: true
      encrypted: true
    key2:
      type: string
      required: true
      encrypted: false
    date_key:
      type: date
      format: YYYY/MM/DD - HH-mm-SS
      required: true
      encrypted: false
    nested_key:
      type: object
      required: true
      keys:
        key3:
            type: string
            required: true
            encrypted: true
        key4:
            type: string
            required: true
            encrypted: false


  identity:
    userId:
      type: long
      required: true
  metadata:
    origin:
      type: string
      required: true


transform:
  hub_xpto:
    key1: $.payload.key1
    created: $.payload.date_key
  satelite_abc:
    user_id: $.identity.userId
    origin: $.metadata.origin
  satelite_def:
    key2: $.payload.key2